// <auto-generated />
namespace DEMO_BANHANG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202012151344273_add-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
